# Generated by Django 2.1.1 on 2018-09-17 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exercise_type', models.CharField(choices=[('RUN', 'RUNNING'), ('FORTIME', 'FORTIME'), ('AMRAP', 'AMRAP'), ('WARMUP', 'ECHAUFFEMENT'), ('STRENGTH', 'FORCE'), ('EMOM', 'EMOM'), ('CONDITIONNING', 'CONDITIONNEMENT'), ('MAX_REP', 'MAXIMUM DE REPETITION')], max_length=20)),
                ('performance_type', models.CharField(choices=[('TIME', 'Temps'), ('NB_ROUNDS', 'Nombre de tours'), ('NB_REP', 'Nombre de repetitions')], max_length=20, null=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="the execrise's creator")),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=20, null=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="the movement's creator")),
            ],
        ),
        migrations.CreateModel(
            name='MovementSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('REP', 'Repetitions'), ('WEIGTH', 'Poids'), ('DISTANCE', 'Distance')], max_length=20)),
                ('unity', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MovementsPerExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_builder.Exercise')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_builder.Movement')),
                ('movement_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_builder.MovementSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="the program's creator")),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="the training's creator")),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='settings',
            field=models.ManyToManyField(related_name='movements', to='program_builder.MovementSettings', verbose_name='list of settings'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movements',
            field=models.ManyToManyField(related_name='exercises', through='program_builder.MovementsPerExercise', to='program_builder.Movement', verbose_name='list of movements per exercise'),
        ),
    ]
