# Generated by Django 2.1.2 on 2018-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='name',
        ),
        migrations.AlterField(
            model_name='movementsettings',
            name='name',
            field=models.CharField(choices=[('repetitions', 'repetitions'), ('poids', 'poids'), ('distance', 'distance'), ('calories', 'calories'), ('lestes', 'lestes')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='performance_type',
            field=models.CharField(choices=[('duree', 'duree'), ('round', 'round'), ('distance', 'distance'), ('anyone', 'anyone')], max_length=20),
        ),
    ]
