# Generated by Django 2.1.2 on 2018-10-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('FORTIME', 'FORTIME'), ('AMRAP', 'AMRAP'), ('WARMUP', 'ECHAUFFEMENT'), ('STRENGTH', 'FORCE'), ('EMOM', 'EMOM'), ('CONDITIONNING', 'CONDITIONNEMENT')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='performance_type',
            field=models.CharField(choices=[('duree', 'duree'), ('round', 'round'), ('distance', 'distance')], max_length=20),
        ),
    ]
