# Generated by Django 2.1.1 on 2018-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0002_auto_20180918_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementsettings',
            name='name',
            field=models.CharField(choices=[('REP', 'Repetitions'), ('WEIGTH', 'Poids'), ('DISTANCE', 'Distance'), ('CAL', 'Calories')], max_length=20, unique=True),
        ),
    ]
