# Generated by Django 2.1.1 on 2018-09-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0003_auto_20180918_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementsperexercise',
            name='movement_number',
            field=models.IntegerField(null=True),
        ),
    ]
