# Generated by Django 2.1.1 on 2018-09-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0004_movementsperexercise_movement_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementsperexercise',
            name='setting_value',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
