# Generated by Django 2.1.1 on 2018-09-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0007_auto_20180920_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementSettingsPerMovementsPerExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_value', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movementsperexercise',
            name='movement_setting',
        ),
        migrations.RemoveField(
            model_name='movementsperexercise',
            name='setting_value',
        ),
        migrations.AddField(
            model_name='movementsettingspermovementsperexercise',
            name='movement_per_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_builder.MovementsPerExercise', verbose_name='the settings value for each movement per exercise'),
        ),
        migrations.AddField(
            model_name='movementsettingspermovementsperexercise',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_builder.MovementSettings', verbose_name='the setting linked to the movement associated to the exercise'),
        ),
        migrations.AddField(
            model_name='movementsettings',
            name='setting_values',
            field=models.ManyToManyField(related_name='exercise_settings', through='program_builder.MovementSettingsPerMovementsPerExercise', to='program_builder.MovementsPerExercise', verbose_name='all the values linked to a setting'),
        ),
        migrations.AddField(
            model_name='movementsperexercise',
            name='movement_settings',
            field=models.ManyToManyField(related_name='exercise_movements', through='program_builder.MovementSettingsPerMovementsPerExercise', to='program_builder.MovementSettings', verbose_name='settings value per movement for one exercise'),
        ),
    ]
