# Generated by Django 2.1.1 on 2018-09-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0008_auto_20180921_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementsettingspermovementsperexercise',
            old_name='movement_per_exercise',
            new_name='exercise_movement',
        ),
    ]
