# Generated by Django 2.1.1 on 2018-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0009_auto_20180921_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementsettingspermovementsperexercise',
            name='setting_value',
            field=models.IntegerField(default=0),
        ),
    ]
