# Generated by Django 2.1.1 on 2018-09-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0010_auto_20180921_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_builder.Equipment', verbose_name='Equipement'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Createur'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='settings',
            field=models.ManyToManyField(related_name='movements', to='program_builder.MovementSettings', verbose_name='Caracteristiques'),
        ),
    ]
