# Generated by Django 2.1.1 on 2018-09-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0011_auto_20180925_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='performance_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('RUN', 'RUNNING'), ('FORTIME', 'FORTIME'), ('AMRAP', 'AMRAP'), ('WARMUP', 'ECHAUFFEMENT'), ('STRENGTH', 'FORCE'), ('EMOM', 'EMOM'), ('CONDITIONNING', 'CONDITIONNEMENT'), ('MAX_REP', 'MAXIMUM DE REPETITIONS')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='performance_type',
            field=models.CharField(choices=[('TIME', 'duree'), ('NB_ROUNDS', 'tours'), ('NB_REP', 'repetitions'), ('DIST', 'distance')], max_length=20, null=True),
        ),
    ]
