# Generated by Django 2.1.1 on 2018-10-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0013_auto_20180928_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='completed',
        ),
    ]
