# Generated by Django 2.1.2 on 2018-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0014_remove_exercise_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
