# Generated by Django 2.1.2 on 2018-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0015_auto_20181004_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'equipement'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'exercice'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name': 'mouvement'},
        ),
        migrations.AlterModelOptions(
            name='movementsettings',
            options={'verbose_name': 'configuration des mouvements'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('FORTIME', 'FORTIME'), ('AMRAP', 'AMRAP'), ('WARMUP', 'ECHAUFFEMENT'), ('STRENGTH', 'FORCE'), ('EMOM', 'EMOM'), ('CONDITIONNING', 'CONDITIONNEMENT'), ('MAX_REP', 'MAXIMUM DE REPETITIONS')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='performance_type',
            field=models.CharField(choices=[('temps', 'temps'), ('round', 'round'), ('repetitions', 'répétitions'), ('distance', 'distance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movementsettings',
            name='name',
            field=models.CharField(choices=[('repetitions', 'repetitions'), ('poids', 'poids'), ('distance', 'distance'), ('calories', 'calories')], max_length=20, unique=True),
        ),
    ]
