# Generated by Django 2.1.2 on 2018-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0016_auto_20181004_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='performance_type',
            field=models.CharField(choices=[('duree', 'duree'), ('round', 'round'), ('repetitions', 'repetitions'), ('distance', 'distance')], max_length=20, null=True),
        ),
    ]
