language: python

python:
  - "3.6"

branches:
  only:
    - master
    - development

before_script:
  - pip install -r requirements.txt

env: 
  - DJANGO_SETTINGS_MODULE="fitperf.settings.travis"
  - EMAIL_HOST_PASSWORD="dev_travis_test"
  - EMAIL_HOST_USER="travis-fitperf@gmail.com"
  - SUPERUSER_EMAIL="superuser@gmail.com"
  - SUPERUSER_PASSWORD="superpassword"
  - SUPERUSER_USERNAME="juliennuellas"
services:
  - postgresql

addons:
  postgresql: "9.4"

script:
  - ./manage.py test