language: python

python:
  - "3.6"

branches:
  only:
    - master
    - development

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="fitperf.settings.travis"

services:
  - postgresql

addons:
  postgresql: "9.4"

script:
  - cd ./manage.py test