# Generated by Django 2.1.2 on 2018-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='goal_type',
            field=models.CharField(choices=[('duree', 'duree'), ('round', 'round'), ('distance', 'distance'), ('anyone', 'anyone')], max_length=20),
        ),
    ]
